/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    ABreadcrumb: typeof import('@arco-design/web-vue')['Breadcrumb']
    ABreadcrumbItem: typeof import('@arco-design/web-vue')['BreadcrumbItem']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ADescriptions: typeof import('@arco-design/web-vue')['Descriptions']
    AList: typeof import('@arco-design/web-vue')['List']
    AListItem: typeof import('@arco-design/web-vue')['ListItem']
    AListItemMeta: typeof import('@arco-design/web-vue')['ListItemMeta']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    BaseFooter: typeof import('./src/client/components/Base/BaseFooter.vue')['default']
    Cropped: typeof import('./src/client/components/Model/Cropped.vue')['default']
    DefaultHeader: typeof import('./src/client/components/Base/DefaultHeader.vue')['default']
    DefaultHeaderNav: typeof import('./src/client/components/Base/DefaultHeaderNav.vue')['default']
    Dialog: typeof import('./src/client/components/Model/Dialog.vue')['default']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElLink: typeof import('element-plus/es')['ElLink']
    EnBreadcrumb: typeof import('./src/client/components/Model/Encapsulation/EnBreadcrumb.vue')['default']
    EnCarousel: typeof import('./src/client/components/Model/Encapsulation/EnCarousel.vue')['default']
    EnCollapse: typeof import('./src/client/components/Model/Encapsulation/EnCollapse.vue')['default']
    EnLazy: typeof import('./src/client/components/Model/Encapsulation/EnLazy.vue')['default']
    EnLink: typeof import('./src/client/components/Model/Encapsulation/EnLink.vue')['default']
    EnSelect: typeof import('./src/client/components/Model/Encapsulation/EnSelect.vue')['default']
    HelloWorld: typeof import('./src/client/components/HelloWorld.vue')['default']
    HotCard: typeof import('./src/client/components/Model/HotCard.vue')['default']
    Income: typeof import('./src/client/components/Model/Income.vue')['default']
    IndexSearch: typeof import('./src/client/components/Model/IndexSearch.vue')['default']
    Markdown: typeof import('./src/client/components/Model/Markdown.vue')['default']
    ModsFilter: typeof import('./src/client/components/Model/ModsFilter.vue')['default']
    PathBreadcrumbs: typeof import('./src/client/components/Path/PathBreadcrumbs.vue')['default']
    PathIndex: typeof import('./src/client/components/Path/PathIndex.vue')['default']
    PathItemFiles: typeof import('./src/client/components/Path/PathItemFiles.vue')['default']
    PathItems: typeof import('./src/client/components/Path/PathItems.vue')['default']
    PathReadme: typeof import('./src/client/components/Path/PathReadme.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
